### ISSUE TITLE
运行时报错，从日志看像是playwright导致的

### ISSUE THREAD

**Issue by pach128** [benx1n/everyday-bangumi#6]
[2023-02-08 15:53:16,185 nonebot] INFO: 正在安装 firefox
[2023-02-08 15:53:16,185 nonebot] INFO: 正在安装依赖
sh: playwright: command not found
[2023-02-08 15:53:16,879 nonebot] INFO: Message -1082937354 is ignored: Handled by PrefixTrigger of Hoshino
[2023-02-08 15:53:17,375 b站动态监视器] INFO: Scheduled job bili_watch start.
/usr/local/python3/lib/python3.8/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
/usr/local/python3/lib/python3.8/site-packages/nonebot/message.py:58: UserWarning: defining message_preprocessor outside a plugin is deprecated and will not be supported in the future
  warnings.warn('defining message_preprocessor outside a plugin is deprecated '
Traceback (most recent call last):
  File "/opt/one-key-xcw/HoshinoBot/hoshino/modules/everyday-bangumi/browser.py", line 17, in init
    _browser = await launch_browser(**kwargs)
  File "/opt/one-key-xcw/HoshinoBot/hoshino/modules/everyday-bangumi/browser.py", line 29, in launch_browser
    return await _playwright.firefox.launch(**kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/playwright/async_api/_generated.py", line 11704, in launch
    await self._async(
  File "/usr/local/python3/lib/python3.8/site-packages/playwright/_impl/_browser_type.py", line 90, in launch
    Browser, from_channel(await self._channel.send("launch", params))
  File "/usr/local/python3/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "/usr/local/python3/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: 
╔════════════════════════════════════════════════════════════╗
║ Host system is missing a few dependencies to run browsers. ║
║ Please install them with the following command:            ║
║                                                            ║
║     playwright install-deps                                ║
║                                                            ║
║ <3 Playwright Team                                         ║
╚════════════════════════════════════════════════════════════╝

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/one-key-xcw/HoshinoBot/hoshino/modules/everyday-bangumi/__init__.py", line 84, in get_today_bangumi
    async with get_new_page() as page:
  File "/usr/local/python3/lib/python3.8/contextlib.py", line 171, in __aenter__
    return await self.gen.__anext__()
  File "/opt/one-key-xcw/HoshinoBot/hoshino/modules/everyday-bangumi/browser.py", line 38, in get_new_page
    browser = await get_browser()
  File "/opt/one-key-xcw/HoshinoBot/hoshino/modules/everyday-bangumi/browser.py", line 33, in get_browser
    return _browser or await init(**kwargs)
  File "/opt/one-key-xcw/HoshinoBot/hoshino/modules/everyday-bangumi/browser.py", line 20, in init
    _browser = await launch_browser(**kwargs)
  File "/opt/one-key-xcw/HoshinoBot/hoshino/modules/everyday-bangumi/browser.py", line 29, in launch_browser
    return await _playwright.firefox.launch(**kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/playwright/async_api/_generated.py", line 11704, in launch
    await self._async(
  File "/usr/local/python3/lib/python3.8/site-packages/playwright/_impl/_browser_type.py", line 90, in launch
    Browser, from_channel(await self._channel.send("launch", params))
  File "/usr/local/python3/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "/usr/local/python3/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: 
╔════════════════════════════════════════════════════════════╗
║ Host system is missing a few dependencies to run browsers. ║
║ Please install them with the following command:            ║
║                                                            ║
║     playwright install-deps                                ║
║                                                            ║
║ <3 Playwright Team                                         ║
╚════════════════════════════════════════════════════════════╝
Traceback (most recent call last):
  File "/opt/one-key-xcw/HoshinoBot/hoshino/modules/everyday-bangumi/__init__.py", line 43, in send_today_bangumi
    await bot.send(ev,str(MessageSegment.image(bytes2b64(img))))
  File "/opt/one-key-xcw/HoshinoBot/hoshino/modules/everyday-bangumi/utils.py", line 27, in bytes2b64
    return f"base64://{b64encode(im).decode()}"
  File "/usr/local/python3/lib/python3.8/base64.py", line 58, in b64encode
    encoded = binascii.b2a_base64(s, newline=False)
TypeError: a bytes-like object is required, not 'NoneType'

**Comment by pach128** [comment]
参考了
